### ISSUE TITLE
Can you generate an exe file? It's troublesome to configure the Fortran language environment

### ISSUE THREAD

**Issue by MsBruce** [TOMOFAST/Tomofast-x#4]
Can you generate an exe file?  It's troublesome to configure the Fortran language environment

**Comment by vogarko** [comment]
Do you mean for Windows?

**Comment by MsBruce** [comment]
> Do you mean for Windows?

Yes, thank you for your reply

**Comment by vogarko** [comment]
Have you tried Windows Subsystem for Linux (WSL)? We are currently supporting Windows builds via the WSL.
Another way is to install the virtual machine (VMWare) with Ubuntu inside (recommended). This way you can build and run Ubuntu applications in Windows.

**Comment by MsBruce** [comment]
> Have you tried Windows Subsystem for Linux (WSL)? We are currently supporting Windows builds via the WSL. Another way is to install the virtual machine (VMWare) with Ubuntu inside (recommended). This way you can build and run Ubuntu applications in Windows.

Thank you ,I will try later.
