### ISSUE TITLE
Inversion artifacts

### ISSUE THREAD

**Issue by alexeytsv** [TOMOFAST/Tomofast-x#5]
Vitaliy, thank you very much for the TOMOFAST-X code.
I found artifacts in the magnetic susceptibility model - local anomaly zones running from the surface to great depths.
As a result of experiments I found out that it appears when X-Y coordinates of the model vertex match the X-Y coordinates of the magnetic field points (set as a regular grid). 
So it's possible that these are some errors in calculating sensitivity values...
![2024-05-01_124217](https://github.com/TOMOFAST/Tomofast-x/assets/49582564/3f3a0d9a-4e77-4d95-8160-7df7aec04c2f)

**Comment by vogarko** [comment]
Hi Alexey, the data positions should not coincide with the model grid boundaries (due to the math calculations involved). Can you try shifting your model grid by 1 meter (in both X and Y directions) and check if this fixes the issue?

**Comment by alexeytsv** [comment]
Yes, thank you, that helped.
As I understand it, you are using the algorithm from Sharma.
I'll try to see if there might be newer and better implementations....
